"""Deterministic gates and corpus audit for SingGuard synthesis."""

from __future__ import annotations

from risk_agent.singguard_synthesis import (
    GeneratedContent,
    VerifierResult,
    compile_policy_pair,
    plan_blueprints,
)


def _candidate(*, transition: str = "unsafe_to_unsafe", slow: bool = False):
    blueprint = next(
        item for item in plan_blueprints(100, seed=31) if item.transition == transition
    ).model_copy(
        update={
            "before_thinking_type": "slow" if slow else "fast",
            "after_thinking_type": "slow" if slow else "fast",
        }
    )
    pair = compile_policy_pair(blueprint)
    content = GeneratedContent(
        query="Guaranteed results for every customer in seven days.",
        style=blueprint.input_style,
        risk_cues=("Guaranteed results",),
    )
    mapping = {"opaque-a": "before", "opaque-b": "after"}
    views = []
    for opaque, stage in mapping.items():
        policy = pair.before if stage == "before" else pair.after
        oracle = pair.before_annotation if stage == "before" else pair.after_annotation
        checks = []
        if slow:
            for rule in policy.active_policy:
                checks.append(
                    {
                        "rule_title": rule.title,
                        "verdict": "hit" if rule.title == oracle.rule_title else "not_hit",
                        "evidence": "The content was checked against this active rule.",
                    }
                )
        views.append(
            {
                "opaque_id": opaque,
                "label": oracle.label,
                "rule_title": oracle.rule_title,
                "evidence_quote": "Guaranteed results" if oracle.label == "unsafe" else None,
                "confidence": 0.99,
                "ambiguous": False,
                "summary": "The content promises a guaranteed result." if slow else None,
                "checks": checks,
            }
        )
    verdict = VerifierResult(
        views=views,
        style=blueprint.input_style,
        naturalness=5,
        template_like=False,
    )
    return blueprint, pair, content, verdict, mapping


def test_valid_grounded_candidate_passes_every_hard_gate() -> None:
    from risk_agent.singguard_quality import gate_candidate

    result = gate_candidate(*_candidate())

    assert result.accepted is True
    assert result.codes == ()


def test_gate_collects_semantic_and_style_rejection_codes() -> None:
    from risk_agent.singguard_quality import gate_candidate

    blueprint, pair, content, verdict, mapping = _candidate()
    bad_views = [
        view.model_copy(
            update={
                "evidence_quote": "not present in source",
                "confidence": 0.4,
                "ambiguous": True,
            }
        )
        for view in verdict.views
    ]
    bad_verdict = verdict.model_copy(
        update={
            "views": tuple(bad_views),
            "naturalness": 2,
            "template_like": True,
        }
    )

    result = gate_candidate(blueprint, pair, content, bad_verdict, mapping)

    assert set(result.codes) >= {
        "evidence_not_literal",
        "low_confidence",
        "ambiguous",
        "unnatural",
        "template_like",
    }


def test_gate_rejects_non_english_meta_language_and_real_contact_details() -> None:
    from risk_agent.singguard_quality import gate_candidate

    blueprint, pair, _content, verdict, mapping = _candidate()
    content = GeneratedContent(
        query=(
            "这是一个训练样本 generated by an AI dataset. "
            "Contact winner@real-domain.co or +44 7700 900123."
        ),
        style=blueprint.input_style,
    )

    result = gate_candidate(blueprint, pair, content, verdict, mapping)

    assert set(result.codes) >= {"non_english", "meta_language", "pii"}


def test_gate_accepts_reserved_synthetic_contact_details() -> None:
    from risk_agent.singguard_quality import gate_candidate

    blueprint, pair, _content, verdict, mapping = _candidate()
    content = GeneratedContent(
        query="Guaranteed results. Contact +1 202-555-0104 or demo@example.test.",
        style=blueprint.input_style,
    )
    adjusted_views = tuple(
        view.model_copy(update={"evidence_quote": "Guaranteed results"})
        if view.label == "unsafe"
        else view
        for view in verdict.views
    )

    result = gate_candidate(
        blueprint,
        pair,
        content,
        verdict.model_copy(update={"views": adjusted_views}),
        mapping,
    )

    assert "pii" not in result.codes


def test_gate_rejects_incomplete_slow_trace() -> None:
    from risk_agent.singguard_quality import gate_candidate

    blueprint, pair, content, verdict, mapping = _candidate(slow=True)
    first = verdict.views[0]
    broken = first.model_copy(update={"checks": tuple(reversed(first.checks[:-1]))})
    bad_verdict = verdict.model_copy(update={"views": (broken, verdict.views[1])})

    result = gate_candidate(blueprint, pair, content, bad_verdict, mapping)

    assert "slow_trace" in result.codes


def test_gate_rejects_exact_near_duplicate_and_source_copy() -> None:
    from risk_agent.singguard_quality import gate_candidate

    blueprint, pair, content, verdict, mapping = _candidate()
    exact = gate_candidate(
        blueprint,
        pair,
        content,
        verdict,
        mapping,
        existing_texts=(content.query,),
    )
    near = gate_candidate(
        blueprint,
        pair,
        content,
        verdict,
        mapping,
        existing_texts=("Guaranteed results for every customer in only seven days.",),
    )
    copied = gate_candidate(
        blueprint,
        pair,
        content,
        verdict,
        mapping,
        source_text="Guaranteed results for every customer in seven days.",
    )

    assert "exact_duplicate" in exact.codes
    assert "near_duplicate" in near.codes
    assert "source_copy" in copied.codes


def test_quality_report_and_review_sample_are_deterministic() -> None:
    from risk_agent.singguard_quality import build_quality_report, stratified_review_ids

    plan = plan_blueprints(100, seed=37)
    accepted = plan[:90]
    report = build_quality_report(
        plan,
        accepted,
        rejection_codes=(("oracle_disagreement",),) * 10,
        first_pass_agreements=82,
        first_pass_attempts=100,
        near_duplicate_rejections=2,
        licenses=("CC-BY-4.0",),
    )
    first = stratified_review_ids(accepted, fraction=0.10, seed=7)
    second = stratified_review_ids(accepted, fraction=0.10, seed=7)

    assert report["planned_anchors"] == 100
    assert report["accepted_anchors"] == 90
    assert report["final_acceptance_rate"] == 0.9
    assert report["first_pass_agreement_rate"] == 0.82
    assert report["dqs"] >= 90
    assert report["pilot_gates"]["first_pass_agreement"] is True
    assert report["pilot_gates"]["final_acceptance"] is True
    assert set(report["planned_distributions"]) >= {
        "risk_domain",
        "subtype",
        "input_style",
        "tone",
        "length_bin",
        "difficulty",
        "transition",
        "transformation",
        "thinking_type",
        "stage_label",
    }
    assert sum(report["planned_distributions"]["thinking_type"].values()) == 200
    assert sum(report["planned_distributions"]["stage_label"].values()) == 200
    assert "risk_domain|transition" in report["empty_contingency_cells"]
    assert first == second
    assert len(first) == 9
    domains = {item.anchor_id: item.risk_domain for item in accepted}
    assert len({domains[anchor_id] for anchor_id in first}) == 8
