"""Deterministic quality gates and corpus-level audits for SingGuard data."""

from __future__ import annotations

import math
import random
import re
import unicodedata
from collections import Counter, defaultdict
from collections.abc import Iterable, Mapping, Sequence
from difflib import SequenceMatcher
from typing import Literal

from pydantic import BaseModel, ConfigDict

from risk_agent.singguard_synthesis import (
    AnchorBlueprint,
    GeneratedContent,
    PolicyPair,
    VerifierResult,
)


class GateResult(BaseModel):
    """Stable result returned by the hard-gate layer."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    accepted: bool
    codes: tuple[str, ...]


_META_PHRASES = (
    "training sample",
    "training example",
    "annotation task",
    "generated by an ai",
    "generated by ai",
    "policy transition",
    "ground truth",
    "local oracle",
    "dataset sample",
)
_EMAIL_RE = re.compile(r"(?i)\b[a-z0-9._%+-]+@([a-z0-9.-]+\.[a-z]{2,})\b")
_PHONE_RE = re.compile(r"(?<!\w)(?:\+?\d[\d ()-]{7,}\d)(?!\w)")
_RESERVED_EMAIL_DOMAINS = ("example.test", "example.com", "example.org", "example.net")
_RESERVED_555_RE = re.compile(r"(?<!\d)(?:\+?1[ .()-]*)?(?:202[ .()-]*)?555[ .()-]*01\d{2}(?!\d)")


def _combined_text(content: GeneratedContent) -> str:
    return "\n".join(part for part in (content.query, content.response) if part)


def _normalized(text: str) -> str:
    return " ".join(re.findall(r"[a-z0-9]+", text.casefold()))


def _char_ngrams(text: str, width: int = 5) -> set[str]:
    normalized = _normalized(text)
    if len(normalized) < width:
        return {normalized} if normalized else set()
    return {normalized[index : index + width] for index in range(len(normalized) - width + 1)}


def _similarity(left: str, right: str) -> float:
    left_grams = _char_ngrams(left)
    right_grams = _char_ngrams(right)
    union = left_grams | right_grams
    return len(left_grams & right_grams) / len(union) if union else 1.0


def _is_english(text: str) -> bool:
    letters = [character for character in text if character.isalpha()]
    if not letters:
        return False
    latin = sum("LATIN" in unicodedata.name(character, "") for character in letters)
    return latin / len(letters) >= 0.95


def _contains_pii(text: str) -> bool:
    for match in _EMAIL_RE.finditer(text):
        if match.group(1).casefold() not in _RESERVED_EMAIL_DOMAINS:
            return True
    for match in _PHONE_RE.finditer(text):
        candidate = match.group(0)
        digits = re.sub(r"\D", "", candidate)
        if len(digits) < 8:
            continue
        if not _RESERVED_555_RE.fullmatch(candidate):
            return True
    return False


def _stage_view(
    verdict: VerifierResult,
    mapping: Mapping[str, Literal["before", "after"]],
) -> dict[str, object]:
    return {
        mapping[view.opaque_id]: view
        for view in verdict.views
        if view.opaque_id in mapping
    }


def _slow_trace_valid(view: object, policy: object, oracle: object) -> bool:
    expected_titles = [rule.title for rule in policy.active_policy]
    checks = list(view.checks)
    if not view.summary or [check.rule_title for check in checks] != expected_titles:
        return False
    hits = {check.rule_title for check in checks if check.verdict == "hit"}
    if oracle.label == "unsafe":
        return oracle.rule_title in hits
    return not hits


def gate_candidate(
    blueprint: AnchorBlueprint,
    pair: PolicyPair,
    content: GeneratedContent,
    verdict: VerifierResult,
    opaque_to_stage: Mapping[str, Literal["before", "after"]],
    *,
    existing_texts: Sequence[str] = (),
    source_text: str | None = None,
) -> GateResult:
    """Apply all hard gates and return every actionable rejection reason."""

    codes: set[str] = set()
    text = _combined_text(content)
    folded = text.casefold()
    if not _is_english(text):
        codes.add("non_english")
    if any(phrase in folded for phrase in _META_PHRASES):
        codes.add("meta_language")
    if _contains_pii(text):
        codes.add("pii")
    if content.style != blueprint.input_style or verdict.style != blueprint.input_style:
        codes.add("style_mismatch")
    if verdict.naturalness < 4:
        codes.add("unnatural")
    if verdict.template_like:
        codes.add("template_like")

    views = _stage_view(verdict, opaque_to_stage)
    if set(views) != {"before", "after"}:
        codes.add("missing_policy_view")
    for stage, policy, oracle, thinking_type in (
        ("before", pair.before, pair.before_annotation, blueprint.before_thinking_type),
        ("after", pair.after, pair.after_annotation, blueprint.after_thinking_type),
    ):
        view = views.get(stage)
        if view is None:
            continue
        if (view.label, view.rule_title) != (oracle.label, oracle.rule_title):
            codes.add("oracle_disagreement")
        active_titles = {rule.title for rule in policy.active_policy}
        if view.rule_title is not None and view.rule_title not in active_titles:
            codes.add("inactive_rule")
        if view.evidence_quote and view.evidence_quote not in text:
            codes.add("evidence_not_literal")
        if view.confidence < 0.85:
            codes.add("low_confidence")
        if view.ambiguous:
            codes.add("ambiguous")
        if thinking_type == "slow" and not _slow_trace_valid(view, policy, oracle):
            codes.add("slow_trace")

    normalized = _normalized(text)
    normalized_existing = {_normalized(item) for item in existing_texts}
    if normalized in normalized_existing:
        codes.add("exact_duplicate")
    elif any(
        _similarity(text, item) >= 0.82
        or SequenceMatcher(None, normalized, _normalized(item)).ratio() >= 0.92
        for item in existing_texts
    ):
        codes.add("near_duplicate")
    if source_text and _similarity(text, source_text) >= 0.75:
        codes.add("source_copy")

    ordered = tuple(sorted(codes))
    return GateResult(accepted=not ordered, codes=ordered)


def _distribution(items: Iterable[AnchorBlueprint], field: str) -> dict[str, int]:
    return dict(sorted(Counter(str(getattr(item, field)) for item in items).items()))


def _blueprint_distributions(items: Sequence[AnchorBlueprint]) -> dict[str, dict[str, int]]:
    distributions = {
        field: _distribution(items, field)
        for field in (
            "risk_domain",
            "subtype",
            "input_style",
            "tone",
            "length_bin",
            "difficulty",
            "transition",
            "transformation",
        )
    }
    distributions["thinking_type"] = dict(
        sorted(
            Counter(
                mode
                for item in items
                for mode in (item.before_thinking_type, item.after_thinking_type)
            ).items()
        )
    )
    labels = {
        "unsafe_to_unsafe": ("before:unsafe", "after:unsafe"),
        "unsafe_to_safe": ("before:unsafe", "after:safe"),
        "safe_to_unsafe": ("before:safe", "after:unsafe"),
        "safe_to_safe": ("before:safe", "after:safe"),
    }
    distributions["stage_label"] = dict(
        sorted(Counter(label for item in items for label in labels[item.transition]).items())
    )
    return distributions


def _empty_domain_transition_cells(items: Sequence[AnchorBlueprint]) -> list[str]:
    domains = sorted({item.risk_domain for item in items})
    transitions = sorted({item.transition for item in items})
    occupied = {(item.risk_domain, item.transition) for item in items}
    return [
        f"{domain}|{transition}"
        for domain in domains
        for transition in transitions
        if (domain, transition) not in occupied
    ]


def build_quality_report(
    planned: Sequence[AnchorBlueprint],
    accepted: Sequence[AnchorBlueprint],
    *,
    rejection_codes: Sequence[Sequence[str]],
    first_pass_agreements: int,
    first_pass_attempts: int,
    near_duplicate_rejections: int,
    licenses: Sequence[str],
) -> dict[str, object]:
    """Build the auditable pilot/final report and its five-part DQS."""

    planned_count = len(planned)
    accepted_count = len(accepted)
    acceptance = accepted_count / planned_count if planned_count else 0.0
    agreement = (
        first_pass_agreements / first_pass_attempts if first_pass_attempts else 0.0
    )
    completeness = acceptance * 100
    consistency = 100.0 if accepted_count else 0.0
    validity = 100.0 if accepted_count else 0.0
    uniqueness = max(
        0.0,
        100.0 - (near_duplicate_rejections / planned_count * 100 if planned_count else 100),
    )
    provenance = 100.0 if licenses else 90.0
    dqs = (
        completeness * 0.30
        + consistency * 0.25
        + validity * 0.20
        + uniqueness * 0.15
        + provenance * 0.10
    )
    rejection_counts = Counter(code for codes in rejection_codes for code in codes)
    return {
        "planned_anchors": planned_count,
        "accepted_anchors": accepted_count,
        "final_acceptance_rate": round(acceptance, 4),
        "first_pass_agreement_rate": round(agreement, 4),
        "dqs": round(dqs, 2),
        "dqs_components": {
            "completeness": round(completeness, 2),
            "consistency": round(consistency, 2),
            "validity": round(validity, 2),
            "uniqueness": round(uniqueness, 2),
            "provenance": round(provenance, 2),
        },
        "pilot_gates": {
            "first_pass_agreement": agreement >= 0.80,
            "final_acceptance": acceptance >= 0.90,
            "dqs": dqs >= 90.0,
        },
        "planned_distributions": _blueprint_distributions(planned),
        "accepted_distributions": _blueprint_distributions(accepted),
        "empty_contingency_cells": {
            "risk_domain|transition": _empty_domain_transition_cells(accepted),
        },
        "rejection_counts": dict(sorted(rejection_counts.items())),
        "license_counts": dict(sorted(Counter(licenses).items())),
    }


def stratified_review_ids(
    accepted: Sequence[AnchorBlueprint],
    *,
    fraction: float = 0.10,
    seed: int,
) -> tuple[str, ...]:
    """Select a deterministic sample while covering every represented domain."""

    if not 0 < fraction <= 1:
        raise ValueError("fraction must be in (0, 1]")
    if not accepted:
        return ()
    sample_size = max(1, math.ceil(len(accepted) * fraction))
    rng = random.Random(seed)
    groups: dict[str, list[AnchorBlueprint]] = defaultdict(list)
    for item in accepted:
        groups[item.risk_domain].append(item)
    selected: list[AnchorBlueprint] = []
    if sample_size >= len(groups):
        for domain in sorted(groups):
            selected.append(rng.choice(sorted(groups[domain], key=lambda item: item.anchor_id)))
    selected_ids = {item.anchor_id for item in selected}
    remainder = sorted(
        (item for item in accepted if item.anchor_id not in selected_ids),
        key=lambda item: item.anchor_id,
    )
    rng.shuffle(remainder)
    selected.extend(remainder[: sample_size - len(selected)])
    return tuple(sorted(item.anchor_id for item in selected))
